title: Michaelwu
email: wuwei_95@outlook.com
description: A fork of @orderlist's Minimal theme, built for Jekyll
baseurl: "/AugustFirst.github.io" 
url: "https://minimal-jekyll.lo/"

markdown: kramdown

sass:
  style: compressed
gems:
  - jekyll-assets

assets:
  compress:
    css: true
    js: true
  prefix: "/assets"
  digest: true

babel_js_extensions: 'es6, babel, jsx'
  
exclude:
  - Gemfile
  - Gemfile.lock
  - /tmp/
  - config.ru

# Development Parameter for Puma 
destination: public