# Site settings
title: MichaelWu's Blog
email: wuwei_95@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  MichaelWu's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: augustfirst.github.io # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: Michael Wu

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
twitter:
weibo: 所静远
github: augustfirst
instagram:
linkedin:

# avatar and Favicon
avatar: http://image.baidu.com/search/detail?ct=503316480&z=undefined&tn=baiduimagedetail&ipn=d&word=%E6%B5%B7%E8%B4%BC%E7%8E%8B%E5%9C%86%E5%A4%B4%E5%83%8F&step_word=&ie=utf-8&in=&cl=2&lm=-1&st=-1&cs=2039972489,758750223&os=1303349632,357421601&simid=3467877400,554219464&pn=24&rn=1&di=43168295390&ln=1995&fr=&fmq=1503133274260_R&fm=rs8&ic=undefined&s=undefined&se=&sme=&tab=0&width=undefined&height=undefined&face=undefined&is=0,0&istype=0&ist=&jit=&bdtype=0&spn=0&pi=0&gsm=0&oriquery=%E7%BB%8F%E5%85%B8%E6%B5%B7%E8%B4%BC%E7%8E%8B%E5%A4%B4%E5%83%8F&objurl=http%3A%2F%2Fs11.sinaimg.cn%2Fmiddle%2F67548fa0gc05dd6e8052a%26690&rpstart=0&rpnum=0&adpicid=0
favicon: assets\img\favicon.jpg

# disqus config
disqus:
  shortname:

# google analytics config


# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
