# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://augustfirst.github.io
date_format: "ordinal"
title: Michaelwu's Blog
subtitle: "Learning computer"
description: "伍威的个人博客"
keywords: Michaelwu, wuwei,computer,algorithm
favicon: /熊.ico
timezone: Asia/China
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Wei Wu
organization: 
organization_url: 
github_username: AugustFirst
location: Chengdu, China
email: wuwei3010@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: augustfirst/augustfirst.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment
comments_provider: gitment
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: 
    repo: 
    oauth:
        client_id: 
        client_secret: 
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
