# Site settings
title: MichaelWu's Blog
email: wuwei_95@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  MichaelWu's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: augustfirst.github.io # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: Michael Wu

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
twitter:
weibo: 所静远
github: augustfirst
instagram:
linkedin:

# avatar and Favicon
avatar: http://b.hiphotos.baidu.com/zhidao/pic/item/f2deb48f8c5494ee81b61a752ef5e0fe98257ec1.jpg
favicon: http://app.files.wptool.cn/c116/116868/TileIcon/17363B97-6E5E-4D2A-8521-CC4CAD74F04A.jpg

# disqus config
disqus:
  shortname:

# google analytics config


# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
