# Site settings
name: Michaelwu's Blog
email: wuwei_95@outlook.com 
author: Michaelwu
url: https://augustfirst.github.io
resume_site: 
github: https://github.com/augustfirst
baseurl: "/AugustFirst.github.io"
description: Learn to write,write to learn.
meta_description: 
motto:而今更笃凌云志，莫教冰鉴负初心
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: AugustFirst
highlighter: Rouge

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

